accounts/urls.py
from django.shortcuts import redirect
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import UserLoginForm
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="registration/login.html", 
                        authentication_form=UserLoginForm, redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.RegistrationView.as_view(), name='register'),
    path('profile/', views.ProfileView.as_view(), name='profile')

]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import IndexPage
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', IndexPage.as_view(), name='index'),
    path('auth/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, unique=True)
    phone = models.CharField(max_length=13 ,blank=True, null=True)
    address = models.CharField(max_length=200 ,blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)

    def __str__(self) -> str:
        return f'Profile for {self.user.first_name}'

accounts/forms.py
from accounts.models import Profile
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.contrib.auth.models import User
# from django.contrib.auth.models import U

class UserLoginForm(AuthenticationForm):
    def __init__(self, *args , **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'h-full-width', 'placeholder': 'Username', 'id': 'username'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'h-full-width',
            'placeholder': 'Password',
            'id': 'password',
        }
))

class RegistrationForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'h-full-width', 'placeholder': 'Username', 'id': 'username'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'h-full-width', 'placeholder': 'First Name', 'id': 'first_name'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'h-full-width', 'placeholder': 'Last Name', 'id': 'last_name'}))
    phone = forms.CharField(widget=forms.NumberInput(attrs={'class': 'h-full-width', 'placeholder': 'Phone', 'id': 'phone'}))
    address = forms.CharField(widget=forms.Textarea(attrs={'class': 'h-full-width', 'placeholder': 'Address', 'id': 'address'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'h-full-width', 'placeholder': 'Email', 'id': 'email'}))
    password = forms.CharField(widget=forms.PasswordInput({'class': 'h-full-width', 'placeholder': 'Password', 'id': 'password'}))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'phone', 'address', 'email', 'password']

class ProfileEditForm(forms.ModelForm):
    phone = forms.CharField(widget=forms.NumberInput(attrs={'class': 'h-full-width', 'placeholder': 'Phone', 'id': 'phone'}))
    address = forms.CharField(widget=forms.Textarea(attrs={'class': 'h-full-width', 'placeholder': 'Address', 'id': 'address'}))

    class Meta:
        model = Profile
        fields = ['phone', 'address']


class UserEditForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'h-full-width', 'placeholder': 'Username', 'id': 'username', 'readonly': True}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'h-full-width', 'placeholder': 'First Name', 'id': 'first_name'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'h-full-width', 'placeholder': 'Last Name', 'id': 'last_name'}))

    class Meta:
        fields = ['username', 'first_name', 'last_name']
        model = User

accounts/views.py
from django.views.generic.detail import DetailView
from accounts.models import Profile
from django.shortcuts import render, redirect
from .forms import ProfileEditForm, RegistrationForm, UserEditForm
# from django.contrib.auth.forms import UserCreationForm
from django.views import View
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from .decorators import login_forbidden
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.urls import reverse
from django.contrib.auth.mixins import  LoginRequiredMixin
from django.contrib import messages

# Create your views here.

@method_decorator(login_forbidden, name='dispatch')
class RegistrationView(View):
    def get(self, request):
        return render(request, 'accounts/register.html', {'form': RegistrationForm})

    def post(self, request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            # save an instance of the data
            new_user = form.save(commit=False)
            # hash the password
            new_user.set_password(cd['password'])

            new_user.save()

            # create a new profile for the new user
            Profile.objects.create(user=new_user)

            return redirect(reverse('index'))

class ProfileView(LoginRequiredMixin, UpdateView):
    login_url = '/auth/login'
    redirect_field_name = 'login'
    template_name = 'accounts/profile.html'
    context_object_name = 'profile'
    fields = ['address', 'phone', ]
    # form_class = RegistrationForm()

    # def get_object(self):
    #     user = get_object_or_404(Profile, user=self.request.user)
    #     print(user)
    #     return user

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['profile_form'] = ProfileEditForm(instance=self.request.user.profile) 
    #     context['user_form'] = UserEditForm(instance=self.request.user)
    #     return context

    # def get_success_url(self) -> str:
    #     url = '/auth/profile'
    #     return url

    def get(self, request):
        profile_form = ProfileEditForm(instance=request.user.profile)
        user_form = UserEditForm(instance=request.user)
        return render(request, 'accounts/profile.html', {'profile_form' : profile_form, 'user_form': user_form})

    def post(self, request):
        profile_form = ProfileEditForm(data=request.POST, instance=request.user.profile, files=request.FILES)
        user_form = UserEditForm(data=request.POST, instance=request.user)
        if profile_form.is_valid() and user_form.is_valid():
            profile_form.save()
            user_form.save()
            messages.success(request, 'Profile was successfully updated')
            print(messages.success(request, 'Profile was successfully updated'))
            return redirect(reverse('accounts:profile'))


# class UpdateProfileView():


        
    # queryset = get_object_or_404(Profile, user=self.request.user)
    # def get_queryset(self):
    #     self.profile = get_object_or_404(Profile, user=self.request.user)
    #     print(self.profile)
    #     return self.profile
    # def get_queryset(self):
    #     return super(ProfileView).get_queryset(self.request, )
    
    # def get(self, request):
        
    #     return render()

accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>Blog - {% block title %} {% endblock %}</title>
    <meta name="description" content="">
    <meta name="author" content="">

   <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/vendor.css' %}">

    <style type="text/css" media="screen">
        .s-styles > .row {
            max-width: var(--width-max);
        }
        .s-styles .intro h1 {
            margin-top: 0;
        }
    </style>

    <!-- script
    ================================================== -->
    <script src="{% static 'js/modernizr.js' %}"></script>

    <!-- favicons
    ================================================== -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'site.webmanifest' %}">

</head>

<body id="top">


    <!-- preloader
    ================================================== -->
    <div id="preloader">
        <div id="loader"></div>
    </div>


    <!-- header
    ================================================== -->
    <header class="s-header">

        <div class="row s-header__content">

            <div class="s-header__logo">
                <a class="logo" href="{% url 'index' %}">
                    <img src="{% static 'images/logo.svg' %}" alt="Homepage">
                </a>
            </div>

            <nav class="s-header__nav-wrap">

                <h2 class="s-header__nav-heading h6">Site Navigation</h2>

                <ul class="s-header__nav">
                    <li><a href="{% url 'index' %}" title="">Home</a></li>
                    <li class="has-children">
                        <a href="#0" title="">Categories</a>
                        <ul class="sub-menu">
                            <li><a href="category.html">Design</a></li>
                            <li><a href="category.html">Lifestyle</a></li>
                            <li><a href="category.html">Photography</a></li>
                            <li><a href="category.html">Vacation</a></li>
                            <li><a href="category.html">Work</a></li>
                            <li><a href="category.html">Health</a></li>
                            <li><a href="category.html">Family</a></li>
                            <li><a href="category.html">Relationship</a></li>
                        </ul>
                    </li>
                    <li class="has-children">
                        <a href="#0" title="">Blog</a>
                        <ul class="sub-menu">
                        <li><a href="single-video.html">Video Post</a></li>
                        <li><a href="single-audio.html">Audio Post</a></li>
                        <li><a href="single-gallery.html">Gallery Post</a></li>
                        <li><a href="single-standard.html">Standard Post</a></li>
                        </ul>
                    </li>
                    <li class="current"><a href="styles.html" title="">Styles</a></li>
                    <li><a href="about.html" title="">About</a></li>
                    <!-- <li><a href="contact.html" title="">Contact</a></li> -->
                    {% if not request.user.is_authenticated %}
                        <li class="has-children">
                            <a href="#0" title="">Account</a>
                            <ul class="sub-menu">
                                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                                <li><a href="{% url 'accounts:register' %}">Create Account</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li class="has-children">
                            <a href="#0" title="">My Account</a>
                            <ul class="sub-menu">
                                <li><a href="{% url 'accounts:profile' %}">My Profile</a></li>
                                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                            </ul>
                        </li>
                    {% endif %}
                </ul> <!-- end header__nav -->

                <a href="#0" title="Close Menu" class="s-header__overlay-close close-mobile-menu">Close</a>

            </nav> <!-- end header__nav-wrap -->
                   
            <a class="s-header__toggle-menu" href="#0" title="Menu"><span>Menu</span></a>
            
            <div class="s-header__search">
                    
                <form role="search" method="get" class="s-header__search-form" action="#">
                    <label>
                        <span class="hide-content">Search for:</span>
                        <input type="search" class="s-header__search-field" placeholder="Type Your Keywords" value="" name="s" title="Search for:" autocomplete="off">
                    </label>
                    <input type="submit" class="s-header__search-submit" value="Search">
                </form>

                <a href="#0" title="Close Search" class="s-header__overlay-close">Close</a>

            </div> <!-- end search wrap -->	

            <a class="s-header__search-trigger" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M10 18a7.952 7.952 0 004.897-1.688l4.396 4.396 1.414-1.414-4.396-4.396A7.952 7.952 0 0018 10c0-4.411-3.589-8-8-8s-8 3.589-8 8 3.589 8 8 8zm0-14c3.309 0 6 2.691 6 6s-2.691 6-6 6-6-2.691-6-6 2.691-6 6-6z"></path></svg>
            </a>

        </div> <!-- end s-header__content -->

    </header> <!-- end header -->

    <section class="s-content s-styles">
        {% block content %}

            

        {% endblock %}
    </section>



    <!-- footer
    ================================================== -->
    <footer class="s-footer">

        <div class="s-footer__main">

            <div class="row">

                <div class="column large-4 medium-6 tab-12 s-footer__info">

                    <h5>About Our Site</h5>

                    <p>
                    Lorem ipsum Ut velit dolor Ut labore id fugiat in ut fugiat nostrud qui in dolore commodo eu magna Duis cillum dolor officia esse mollit proident Excepteur exercitation nulla. Lorem ipsum In reprehenderit commodo aliqua irure labore.
                    </p>

                </div> <!-- end s-footer__info -->

                <div class="column large-2 medium-3 tab-6 s-footer__site-links">

                    <h5>Site Links</h5>

                    <ul>
                        <li><a href="#0">About Us</a></li>
                        <li><a href="#0">Blog</a></li>
                        <li><a href="#0">FAQ</a></li>
                        <li><a href="#0">Terms</a></li>
                        <li><a href="#0">Privacy Policy</a></li>
                    </ul>

                </div> <!-- end s-footer__site-links -->  

                <div class="column large-2 medium-3 tab-6 s-footer__social-links">

                    <h5>Social</h5>

                    <ul>
                        <li><a href="#0">Twitter</a></li>
                        <li><a href="#0">Facebook</a></li>
                        <li><a href="#0">Dribbble</a></li>
                        <li><a href="#0">Pinterest</a></li>
                        <li><a href="#0">Instagram</a></li>
                    </ul>

                </div> <!-- end s-footer__social links --> 

                <div class="column large-4 medium-12 s-footer__subscribe">

                    <h5>Subscribe</h5>

                    <p>Keep yourself updated. Subscribe to our newsletter.</p>

                    <div class="subscribe-form">
                
                        <form id="mc-form" class="group" novalidate="true">

                            <input type="email" value="" name="dEmail" class="email" id="mc-email" placeholder="Type &amp; press enter" required=""> 
                
                            <input type="submit" name="subscribe" >
                
                            <label for="mc-email" class="subscribe-message"></label>
                
                        </form>

                    </div>

                </div> <!-- end s-footer__subscribe -->

            </div> <!-- end row -->

        </div> <!-- end s-footer__main -->

        <div class="s-footer__bottom">
            <div class="row">
                <div class="column">
                    <div class="ss-copyright">
                        <span>© Copyright Abstract 2020</span> 
                        <span>Design by <a href="https://www.styleshout.com/">StyleShout</a></span>		         	
                    </div> <!-- end ss-copyright -->
                </div>
            </div> 

            <div class="ss-go-top">
                <a class="smoothscroll" title="Back to Top" href="#top">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M6 4h12v2H6zm5 10v6h2v-6h5l-6-6-6 6z"/></svg>
                </a>
            </div> <!-- end ss-go-top -->
        </div> <!-- end s-footer__bottom -->

   </footer> <!-- end s-footer -->


   <!-- Java Script
   ================================================== --> 
   <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
   <script src="{% static 'js/plugins.js' %}"></script>
   <script src="{% static 'js/main.js' %}"></script>

</body>

</html>